### ISSUE TITLE
Setup of maip 

### ISSUE THREAD

**Issue by Tim-Cunnane** [Montimage/maip#1]
Hi, I am currently in the process of setting up the maip platform on the VM, however I am having a couple of issues with this. I have the UI started but if I go into any section of the system it will say error{} in the top right corner of the screen. 
Would you be able to give me a hand with this?

Thanks

**Comment by strongcourage** [comment]
Hello Tim, 

Did you install it by running the script or using the Dockerfile? On which system did you perform the installation? I have only tested it on Ubuntu 20.04.6 LTS - Focal. If possible, can you share a screenshot of the error?

Best,
Manh

**Comment by Tim-Cunnane** [comment]
Hi Manh,

I have ran the start-client.sh scrip and I am able to get on to the UI. I am running it on a Ubuntu 20.04.6 LTS-focal. I have attached image below of the error when trying to get into the all arrears of the system like build, models, predict, etc. 

![IMG_1449](https://github.com/Montimage/maip/assets/98821034/a1503aef-ad28-40d0-bc33-e0ecd091c559)
![IMG_1450](https://github.com/Montimage/maip/assets/98821034/2f21ca62-9acc-4476-a8a0-e2139b0b2b1a)

Thanks for any help 
Tim

**Comment by strongcourage** [comment]
Hi Tim,

It seems that you have not started the server yet. Please make sure you run the script `start-maip.sh` first on one terminal and then the script `start-client.sh` on another terminal.

Best,
Manh

**Comment by Tim-Cunnane** [comment]
Hi, 

ahhhh perfect, that is sorted now appreciate it 

Appreciate the help with this.

Thanks,
Tim

**Comment by Tim-Cunnane** [comment]
Hi, 

Apologies now whenever I build a new model it doesn’t appear within the all model section. 

Also when i change from activity classification to anomaly detection and then I change to build a model it will automatically revert back to activity classification.

Best,
Tim

**Comment by strongcourage** [comment]
Sorry, changing the app on client side is not handled properly now. I will fix this issue soon to make the state “app” more persistent on page navigation. If you want to change the AI application, please update [this line](https://github.com/Montimage/maip/blob/main/src/client/src/reducers/appReducer.js#L4) with values `ad` or `ac` (by default). Also keep in mind that the repo is under development :D.

**Comment by Tim-Cunnane** [comment]
Hi, 

Just want to check are we able to build model on the client side becuase when I build a model, it say that it is successfully built but in the All models section there is none within the section

Thanks

**Comment by strongcourage** [comment]
You are trying to build models for which applications? For activity classification ('ac'), it normally takes several seconds to build a model. For 'ad', it takes a bit longer, several minutes to complete, especially if you upload pcap files. You can also check the log on the terminal where you are running the server to see if there are any problems. Perhaps, you can start with the [pcap files](https://github.com/Montimage/maip/tree/main/pcaps) first.

**Comment by Tim-Cunnane** [comment]
trying to bulid models for 'ad', I built a model about 15 minutes ago with the existing pcaps provided and the system indicated that the model was successfully built, however there is no models within the All models section of the system which is a bit strange as seen in the below
![image](https://github.com/Montimage/maip/assets/98821034/009294bd-b459-442e-aaa4-2c375c074b1c)

**Comment by strongcourage** [comment]
I guess you may encounter some issues in parsing the upload pcap files. I just checked and can build models on my local machine. Thus, I recently added the [mmt's reports of 2 pcap files](https://github.com/Montimage/maip/tree/main/src/server/mmt/outputs), so that you can select them without uploading pcap files (commit [993b4cb](https://github.com/Montimage/maip/commit/993b4cbd2f4bc05a334ab049ccdfc32df9e5035c)).
<img width="671" alt="Screenshot 2023-11-17 at 12 44 01" src="https://github.com/Montimage/maip/assets/9584484/fde33246-c475-443c-ac7e-1421d061e4f3">
On the server, you should see the log like this:
<img width="892" alt="Screenshot 2023-11-17 at 12 45 50" src="https://github.com/Montimage/maip/assets/9584484/32332379-8696-4fbe-84a3-a80b4c2f0570">
Finally, after 1 or 2 minutes, you should see the newly built model in the table of all models.
<img width="801" alt="Screenshot 2023-11-17 at 12 46 13" src="https://github.com/Montimage/maip/assets/9584484/82630210-8db1-4e8c-b9ac-6c6a4146b6fb">
At least, running the latest version, you should see the [model `model_2`](https://github.com/Montimage/maip/tree/main/src/server/deep-learning/models) there (for performance testing purpose). Hope this helps.

**Comment by Tim-Cunnane** [comment]
Hi,

Hope you had a good Christmas

I am still have issue with the building of the models and they are not appearing in the All models section. Once I build the model the logs will appear like the below:
![image](https://github.com/Montimage/maip/assets/98821034/bf026f26-1ff0-43b9-bcb9-f4a471f7a98c)

It has the POST requests however there is no GET requests. Would you now why this would be happening?
Any help would be appreciated 

Thanks,
Tim

**Comment by strongcourage** [comment]
Hi Tim,

First, you need to check whether there are any issues in the model building process in the log `training_f3044...log`. If everything is ok, you will see the new model located at `deep-learning/models` or you can run the GET request `/models`.

Hope this helps.

**Comment by Tim-Cunnane** [comment]
Hi,

![image](https://github.com/Montimage/maip/assets/98821034/7d347e54-671e-4a2b-b223-e85e9e31a8fb)
get this module not found error, how would this be installed?

**Comment by strongcourage** [comment]
Hello,
I see, please follow this script to install necessary python libraries: https://github.com/Montimage/maip/blob/main/install.sh#L13C1-L13C55. Also pay attention to the version of Python 3. If you installed it on Ubuntu 20.04, it should be fine.

**Comment by Tim-Cunnane** [comment]
Hi,

I am receiving this after all of the modules have been installed and I have tried to build a model, just wondering if you have seen this issue before.
![image](https://github.com/Montimage/maip/assets/98821034/893c98a3-6527-4292-8cbf-aeabf9cd49bb)

**Comment by edmdo** [comment]
AVX needs to be supported by the CPU. Try this: https://stackoverflow.com/questions/58198180/run-tensorflow-2-0-on-cpu-without-avx

**Comment by Tim-Cunnane** [comment]
Would it be possible if you could create a model with the latest reports for normal traffic and bot traffic in ad and change the training parameters to be different than the model that is pushed already?  

Let me know if this is possible.

**Comment by Tim-Cunnane** [comment]
Just checking if the above is possible?

Thanks 
Tim

**Comment by strongcourage** [comment]
Hi Tim,

Yes, we can build new models by fine-tuning the parameters, such as the number of epochs and the size of batches for CNN and SAE. This should be done using the POST request /build or on "Build Model" tab.

**Comment by Tim-Cunnane** [comment]
Hi, 

perfect, currently having issues with the avx instructions as it is saying that it isn’t supported on my devices, so trying to get something sorted for as I am currently a final year uni student looking into this software. 

Would you know the params that are used for the model 2 that is already in the repo in anomaly detection section

**Comment by strongcourage** [comment]
I think that you can generally ignore this warning concerning avx instructions, and TensorFlow should still run as expected on your system, please check. 

The model_2 is built as shown in the video demo with following parameters: number of epochs for CNN 5, number of epochs for SAE 2, size of batches for CNN 16, size of batches for SAE 32. The video showed that using 2 epochs for the SAE resulted in better performance compared to using 3 epochs for the tested training pcaps.

**Comment by Tim-Cunnane** [comment]
![image](https://github.com/Montimage/maip/assets/98821034/b949e2ad-be82-449d-8b13-c38451c0d1d8)
Get this within the logs of the system whenever I build a model and after checking the all model there is no model that are appearing. Just wanting to check what way do you find is best to start the platform, to allow for me to be able to build a model.

![image](https://github.com/Montimage/maip/assets/98821034/54241bd6-4786-4642-936b-27fae8d90bc8)
![image](https://github.com/Montimage/maip/assets/98821034/91b390d5-525f-4039-8eee-deab5386433a)
I ran the server with the using the installation instruction on the website

**Comment by Tim-Cunnane** [comment]
Would you have a break down of the exact AI python libraries that are used with in the system? and how they are used?

**Comment by strongcourage** [comment]
Sorry, it seems that you need to fix this issue in order to run tensorflow. According to [this](https://github.com/tensorflow/tensorflow/issues/24548), what you can try is to uninstall tensorflow and then install tensorflow-cpu version 2.11.0.

All python libraries I've used are here https://github.com/Montimage/maip/blob/main/src/server/deep-learning/requirements.txt: lime and shap for XAI, the rest for extracting features, building and running AI models.

**Comment by Tim-Cunnane** [comment]
That is no problem I will have to look into it in the mean time,  Would it be possible to upload a model that has the 3 epochs for SAE and different batch size than the one that is upload just for testing purposes?

**Comment by strongcourage** [comment]
Sure, I uploaded this model [here](https://github.com/Montimage/maip/tree/main/src/server/deep-learning/models).

**Comment by Tim-Cunnane** [comment]
Thank you for all of your help appreciate it

**Comment by Tim-Cunnane** [comment]
Hi, 

There currently is an issue with the model 1 that was uploaded as there is no building status within the training folder how would this be fixed or could this be fixed.
![image](https://github.com/Montimage/maip/assets/98821034/f9e9ad87-9e9a-4d56-ad86-808710673395)

**Comment by Tim-Cunnane** [comment]
Hi,

Would you have the pcap that you have used for the predict section that I could use for testing purposes, these include the youtube pcap, web cairn.pcap and the botnet honeypot.pcap?

**Comment by strongcourage** [comment]
Hi Tim,

Sorry, I forgot adding building files of `model_1`, please check the commit [c50315f](https://github.com/Montimage/maip/commit/c50315f4005b47156c9f74088fbd34a075db0b31). Also, please find the pcaps [here](https://github.com/Montimage/maip/tree/main/pcaps) for testing. You can also use [normal pcaps](https://github.com/Montimage/activity-classification/tree/master/real_pcap) or malicious pcaps by searching for `"botnet pcap files"` on Internet.

Best.

**Comment by Tim-Cunnane** [comment]
Hi,

No bother, appreciate your help 

Thanks,

**Comment by Tim-Cunnane** [comment]
Hi,

Sorry for hassling so much, I am having issue with the predict section when a model is picked and I add a pcap file then click predict, the system seem to be unresponsive would there be any reason for this?

**Comment by Tim-Cunnane** [comment]
Hi, 

There is also issues with the SHAP and LIME where I am getting a 304 response error with the model. Have you seen this before?
![image](https://github.com/Montimage/maip/assets/98821034/e7ff0f4c-b4fe-473e-94b8-cd1cbd4a55c9)


Thanks

**Comment by strongcourage** [comment]
Hi Tim,

As you don't use the GUI, for prediction, you need to run 2 APIs in sequence as follows:
1) `POST /mmt/offline` to produce analysis report of existing pcap files in `/maip/pcaps/`, for example with the body request:
```
{
  "fileName": "youtube7.pcap"
}
```
If ok, you will find the reports in csv in the folder `/maip/src/server/mmt/outputs/`. In case you want to upload a new pcap file, please use the `POST /pcaps` request.

2) `POST /predict` using the following body request for `youtube7.pcap`:
```
{
  "predictConfig": {
    "modelId": "model_1",
    "inputTraffic": {
      "type": "report",
      "value": {
        "reportId": "report-youtube7.pcap-624b4fe1-422c-4b81-bc4a-2d3a47919b8a",
        "reportFileName": "1695745314.129769_0_youtube7.pcap.csv"
      }
    }
  }
}
```

I plan to improve the `POST /predict` to support `"type": "pcap"` so that the first POST request is executed automatically. 

I added the reports of 3 testing pcap files in the latest commit so that you don't need to run the first step for those pcap files.

Regarding the issues of XAI, can you provide the logs? Thanks.

**Comment by Tim-Cunnane** [comment]
Hi,

How would you start the GUI to allow for me to use the predict if that would be easier?

This is what I am seeing on the logs for the XAI
![image](https://github.com/Montimage/maip/assets/98821034/7c04e3b1-b5c3-4f1c-a100-c5af4e5bdd3a)

**Comment by strongcourage** [comment]
Producing SHAP explanations can take a significant amount of time, even hours/days, depending on the size of the dataset or the number of samples being explained. I'd recommend running LIME first, as it is fast. You see several `GET /api/xai` requests, which are intended to continuously track the status of the XAI process. You can wait for the XAI process to complete and then disregard those GET requests. 

To initiate the GUI, start the server first and then the client, following the steps you've already executed. Hope that helps.

**Comment by Tim-Cunnane** [comment]
Hi,

That is no bother at all, will have to run it and leave it, just want to be sure, is this likely to be the same for the attacks as it is getting the same responses in the logs

![image](https://github.com/Montimage/maip/assets/98821034/471f70a6-6603-4308-939f-b4f9a3ebe6e2)

Apologies I miscommunication i am on the GUI trying to run the task but they just have the loading wheel

**Comment by Tim-Cunnane** [comment]
Hi,

Hope you are keeping well,

Just looking to see if there is any information in the pcap files that have been uploaded to the repo in terms of:

What traffic is used within the pcaps?
For the bot pcap what network attack utilised such as DDOS or Denial of Service? 
and for the honeypot pcap where is this obtained?

Hopefully you will be able to help me.

Thanks
Tim

**Comment by strongcourage** [comment]
Hello Tim,

The pcap files are extracted from [this public dataset](https://www.unb.ca/cic/datasets/ids-2018.html). The botnet attacks may consist of remote shell, file upload/download, capturing screenshots and key logging, etc. The example honeypot pcap can be obtained from multiple sources, like our honeypots or public datasets. Hope this help.

Best.

**Comment by Tim-Cunnane** [comment]
Hi,

Hope you are keeping well.

I am currently in the process of trying to create models for analyzing the best model parameters for my dissertation to show the accuracy numbers and F1 score for all of the models , apart from the 2 already made within the repo. I was wondering if it would be possible for some more model to be created and added to the repo. 

Please see below the model that i would need created. 
[models.txt](https://github.com/Montimage/maip/files/14319078/models.txt)

I appreciate all of the help and hope that this is possible to be completed.

Thanks
Tim

**Comment by Tim-Cunnane** [comment]
Hi, 

Just want to check if the above is possible?

Thanks

**Comment by strongcourage** [comment]
Hi Tim,

I will try to build those models this week.

Best,

**Comment by Tim-Cunnane** [comment]
Hi, 

thank you very much, appreciate you help.

Kind regards

**Comment by strongcourage** [comment]
Hello Tim,

I recently built different models you've requested (https://github.com/Montimage/maip/commit/413de42aa85ab4b7fa5657ae7d3ee60b2d19fd3c). Please share with us if you find any interesting results during your testing phase, e.g., which configurations perform best. Thank you.

<img width="811" alt="Screenshot 2024-02-23 at 09 53 57" src="https://github.com/Montimage/maip/assets/9584484/b893407e-e0a4-433a-8569-7d4a5bf9a817">


Best.

**Comment by Tim-Cunnane** [comment]
Hi, 

Thanks for this, I am also currently trying to run a gan drvien attack on model 2 to test the robustness and get the performance score. how long would this usually take as this has been running quite a while for me so far?

Also, at the start of the attack there was a few errors that came up on GUI but then went away would this be a problem?

Thanks

**Comment by strongcourage** [comment]
Hello Tim, 

Thank you for reporting the bugs. I fixed it in the latest commit, so that you can run all 3 attacks against `model_2`. Actually I added the dataset generated using CTGAN [dataset](https://github.com/Montimage/maip/blob/main/src/server/deep-learning/attacks/model_2/ctgan_samples.csv) for `model_2`. I will later update the API to automatically produce those GAN datasets with different configurations.

Since you're currently playing with our tool, if it's ok for you, I'll soon share our evaluation google form with you via email. Thus, you can provide us with your feedback to help us improve the tool. Thanks.

Best,

**Comment by Tim-Cunnane** [comment]
Hi,

Just out of curiosity, how would would this usually take to complete the CTGAN attack becuase i have been running it for a couple of hours now? I am trying to get the resilience scores from before and after the attack on model 2.  

Thanks

**Comment by strongcourage** [comment]
Hello,

It's matter of seconds, around 10s. I would suggest you check the server logs to see if there are any errors.
My logs are as follows:
```
[SERVER] MAIP Server started on: http://0.0.0.0:31057
GET /api/models 200 56.496 ms - -
GET /api/models 304 32.456 ms - -
/home/strongcourage/maip/src/server/deep-learning/trainings/model_2/datasets/Train_samples_view.csv
GET /api/models/model_2/datasets/train/view 200 280.014 ms - -
OPTIONS /api/attacks/poisoning/ctgan 204 0.257 ms - 0
Command to be coppied
python3 /home/strongcourage/maip/src/server/deep-learning//attacks.py model_2 ctgan 20
POST /api/attacks/poisoning/ctgan 200 22.589 ms - 94
GET /api/attacks 200 0.835 ms - 112
GET /api/attacks 304 0.493 ms - -
Process has completed:  python3 [
  '/home/strongcourage/maip/src/server/deep-learning//attacks.py',
  'model_2',
  'ctgan',
  20,
  ''
]
The log can be found at:  /home/strongcourage/maip/src/server/logs/attacks_ctgan_model_2_20.log
Going to callback on closed
Finish performing poisoning attack using CTGAN
GET /api/attacks 200 0.282 ms - 113
/home/strongcourage/maip/src/server/deep-learning/attacks/model_2/ctgan_poisoned_dataset.csv
GET /api/attacks/poisoning/ctgan/model_2/view 200 196.298 ms - -
GET /api/models 304 3.205 ms - -
OPTIONS /api/models/model_2 204 0.144 ms - 0
OPTIONS /api/models/model_2/predictions 204 0.117 ms - 0
OPTIONS /api/models/model_2/build-config 204 0.320 ms - 0
GET /api/attacks/model_2/datasets 200 6.501 ms - 117
GET /api/models/model_2/predictions 200 5.896 ms - -
GET /api/models/model_2/build-config 200 6.210 ms - 544
1695736470832
GET /api/models/model_2 200 22.546 ms - -
OPTIONS /api/retrain/model_2 204 0.232 ms - 0
model_2
{
  trainingDataset: 'ctgan_poisoned_dataset.csv',
  testingDataset: 'Test_samples.csv',
  training_parameters: {
    nb_epoch_cnn: 5,
    nb_epoch_sae: 2,
    batch_size_cnn: 16,
    batch_size_sae: 32
  }
}
{
  modelId: 'model_2',
  trainingDataset: 'ctgan_poisoned_dataset.csv',
  testingDataset: 'Test_samples.csv',
  training_parameters: {
    nb_epoch_cnn: 5,
    nb_epoch_sae: 2,
    batch_size_cnn: 16,
    batch_size_sae: 32
  }
}
{
  modelId: 'model_2',
  trainingDataset: 'ctgan_poisoned_dataset.csv',
  testingDataset: 'Test_samples.csv',
  training_parameters: {
    nb_epoch_cnn: 5,
    nb_epoch_sae: 2,
    batch_size_cnn: 16,
    batch_size_sae: 32
  }
}
/home/strongcourage/maip/src/server/deep-learning/trainings/310bc008-a58d-4811-8f1d-fa30f2dfd414/
/home/strongcourage/maip/src/server/deep-learning/trainings/model_2/datasets/Test_samples.csv
/home/strongcourage/maip/src/server/deep-learning/attacks/model_2/ctgan_poisoned_dataset.csv
/home/strongcourage/maip/src/server/deep-learning/trainings/model_2/datasets/Test_samples.csv
Command to be coppied
python3 /home/strongcourage/maip/src/server/deep-learning//retrain.py /home/strongcourage/maip/src/server/deep-learning/attacks/model_2/ctgan_poisoned_dataset.csv /home/strongcourage/maip/src/server/deep-learning/trainings/model_2/datasets/Test_samples.csv /home/strongcourage/maip/src/server/deep-learning/trainings/310bc008-a58d-4811-8f1d-fa30f2dfd414/results 5 2 16 32
{
  retrainConfig: '/home/strongcourage/maip/src/server/deep-learning/trainings/310bc008-a58d-4811-8f1d-fa30f2dfd414/retrain-config.json',
  retrainId: '310bc008-a58d-4811-8f1d-fa30f2dfd414'
}
POST /api/retrain/model_2 200 29.039 ms - 187
GET /api/retrain 200 0.664 ms - 333
GET /api/retrain 304 0.405 ms - -
GET /api/retrain 304 0.451 ms - -
GET /api/retrain 304 0.424 ms - -
GET /api/retrain 304 0.396 ms - -
GET /api/retrain 304 0.381 ms - -
GET /api/retrain 304 0.335 ms - -
GET /api/retrain 304 0.333 ms - -
GET /api/retrain 304 0.295 ms - -
GET /api/retrain 304 0.291 ms - -
GET /api/retrain 304 0.577 ms - -
GET /api/retrain 304 0.459 ms - -
Process has completed:  python3 [
  '/home/strongcourage/maip/src/server/deep-learning//retrain.py',
  '/home/strongcourage/maip/src/server/deep-learning/attacks/model_2/ctgan_poisoned_dataset.csv',
  '/home/strongcourage/maip/src/server/deep-learning/trainings/model_2/datasets/Test_samples.csv',
  '/home/strongcourage/maip/src/server/deep-learning/trainings/310bc008-a58d-4811-8f1d-fa30f2dfd414/results',
  5,
  2,
  16,
  32
]
The log can be found at:  /home/strongcourage/maip/src/server/logs/retraining_310bc008-a58d-4811-8f1d-fa30f2dfd414.log
Going to callback on closed
Finish retraining the model
GET /api/retrain 200 0.266 ms - 334
OPTIONS /api/models/310bc008-a58d-4811-8f1d-fa30f2dfd414/predictions 204 0.175 ms - 0
GET /api/models/310bc008-a58d-4811-8f1d-fa30f2dfd414/predictions 200 0.939 ms - -
```

**Comment by Tim-Cunnane** [comment]
Hi, 
That is strange this is what I am getting 

![IMG_1584](https://github.com/Montimage/maip/assets/98821034/9a5612a8-163b-4ced-9c33-971404a70432)
 
 would you know why?

Thanks Tim

**Comment by Tim-Cunnane** [comment]
Apologise it is now this,

![image](https://github.com/Montimage/maip/assets/98821034/e8956507-f305-4b7e-8880-47032d227cdf)

**Comment by strongcourage** [comment]
I see, you failed to produce the poisoning dataset of the [GAN-based dataset](https://github.com/Montimage/maip/blob/main/src/server/deep-learning/attacks/model_2/ctgan_samples.csv). First, please make sure you get the latest version of code. Check again if the `ctgan_samples.csv` located in the folder `/maip/src/server/deep-learning/attacks/model_2` on your machine. Then, run again the server. If you perform successfully the GAN attack, you should see two new csv on the same folder: `ctgan_poisoned_dataset.csv` and `ctgan_poisoned_dataset_view.csv` (for visualization purpose only). 
Hope that helps!

**Comment by Tim-Cunnane** [comment]
Hi, 

Ahh got it sorted thank you for you help. How long does it usually take to get the resilience metrics for before and after the attack.

Just to let you know the node modules folder isn't on the repo anymore which stop me from getting on the the GUI

Thanks,
Tim

**Comment by Tim-Cunnane** [comment]
Hi,

Sorry to be a hassle, How long does it usually take to get the resilience metrics for before and after the attack?
Getting the sort of thing with the logs 
![Uploading image.jpg…]()

Thanks,
Tim

**Comment by strongcourage** [comment]
The entire process (producing a poisoned GAN dataset and computing resilience metrics) took around 10-15 seconds. The second step involves retraining the model using the poisoned dataset generated from the first step. Both steps depend on the size of the GAN dataset; however, in this case, it is quite fast.

**Comment by Tim-Cunnane** [comment]
I have been running the resilience for quite a while now would there be any specific reason why it would be taking longer to complete.

Thanks

**Comment by strongcourage** [comment]
@Tim-Cunnane: Can you please provide a copy of the server log when you compute the resilience metrics? It is difficult for me to debug without it. If you want compute resilience metrics for other models (not `model_2`), you may need to copy the GAN dataset `ctgan_samples.csv` to the corresponding folder of the tested model in `/attacks`.

**Comment by Tim-Cunnane** [comment]
The server is below:
![image](https://github.com/Montimage/maip/assets/98821034/f1cef5b3-053f-4b35-bad0-d2d960eb0d97)

**Comment by Tim-Cunnane** [comment]
I also receive this error sometimes when start the resilience metric:
![image](https://github.com/Montimage/maip/assets/98821034/28c235a2-9df2-41a6-a6aa-d8a4f7215cf4)

**Comment by strongcourage** [comment]
@Tim-Cunnane: It's a bit strange as I have not encountered this issue. Please check again if the poisoned GAN dataset is successfully generated as below. Also, calculating the resilience metrics requires retraining the model. I'm not sure if the problem is due to your hardware issues.

<img width="842" alt="Screenshot 2024-03-07 at 11 48 43" src="https://github.com/Montimage/maip/assets/9584484/ecc5e39d-8838-4bb7-a689-f2b01d2eb95b">

**Comment by Tim-Cunnane** [comment]
Hi,

Yeah all of the poisoned dataset are there within that folder. I think i may have found the issue where it is the AVX instruction but i have install the link that you suggest in the above comment and i am getting this when running the client of MAIP would there be any specific reason for this? The repo is fully up-to-date
![image](https://github.com/Montimage/maip/assets/98821034/83a9cbab-e39c-4f7b-9510-e813cc35c710)

![image](https://github.com/Montimage/maip/assets/98821034/1b2583a7-0a5b-4c1b-b90e-a791f32b30a2)



Thanks

**Comment by Tim-Cunnane** [comment]
Stange why the above is happen and i am stuggling to figureout the reason for this.


Thanks

**Comment by strongcourage** [comment]
Sorry Tim, unfortunately I don't have a solution for the hardware issue as it worked totally fine for me.

**Comment by Tim-Cunnane** [comment]
That is not a bother, just wanted to check what type of AVX instruction does the CPU need to be compatible for such as AVX512, AVX1 or 2?

**Comment by Tim-Cunnane** [comment]
What CPU do you have to allow for this to be completed?

Thanks

**Comment by Tim-Cunnane** [comment]
please see below issue when running the client. I have clone the repo to ensure that this actually an issue with the repo and this is what appears:

![image](https://github.com/Montimage/maip/assets/98821034/e0940c89-6e82-4907-91df-6c9f6fb1e3f3)
 
Sorry for the hassle

Thanks,
Tim

**Comment by Tim-Cunnane** [comment]
Hi, 

Sorry i believe that i have found a laptop that will allow me to be able complete the tasks. I came across an issue when installing the nodejs using this command curl -sL https://deb.nodesource.com/setup_19.x | bash

I am receiving this error:
![image](https://github.com/Montimage/maip/assets/98821034/9a004dcb-b1a9-4703-a7a1-6f99dccb77c8)

I was wondering if you would know a fix to this issue?

Appreciate any help that you give me.

Thanks

**Comment by strongcourage** [comment]
Nice try. You can copy the error message on google, I found [this potential solution](https://unix.stackexchange.com/questions/385860/could-not-open-lock-file-var-lib-apt-lists-lock-open-13-permission-denied).
```
... | sudo bash
```
Hope this works.

**Comment by Tim-Cunnane** [comment]
Hi, 

Thank you for all of your help, Just want to see if you had any other pcaps from the public dataset that you got the botnet pcap from such as the DDos attack or DoS, etc.

Thanks
