### ISSUE TITLE
RCA app

### ISSUE THREAD

**Issue by benaneli2024** [Montimage/maip#2]
Hello @strongcourage,

Thanks for sharing MAIP and its detailed documentation.

I'd like to know more about RCA application. After reading the code, I understand that it is a separated tool running on localhost. I just wanted to know if this application is integrated into MAIP and the code is available elsewhere. 

I apologize if this has been documented already! I would appreciate any advice you could provide. Thank you.

Best,

**Comment by strongcourage** [comment]
Hi @benaneli2024,

Thank you for your interest in our tool. You're right, currently, RCA is a separate tool with its own GUI. You can have a look at this repo https://github.com/Montimage/rca. We are working to make it more generic and plan to integrate it into MAIP soon. Our goal is to combine 2 or even 3 applications (user activity classification, anomaly detection, and RCA) into a workflow/use case, as these applications have close relationships. For example, outputs or datasets from one application can serve as input for another.

Best regards,
Manh

**Comment by strongcourage** [comment]
@benaneli2024: could you please help fill in this survey related to MAIP as mentioned [here](https://github.com/Montimage/maip/issues/5). Thank you very much in advance.

**Comment by benaneli2024** [comment]
@strongcourage: done
