### ISSUE TITLE
Questions on XAI SHAP

### ISSUE THREAD

**Issue by benaneli2024** [Montimage/maip#3]
Hello, 

I ran the XAI SHAP method to obtain the list of feature importance. It was quite fast for the user activity classification. However, for the anomaly detection application, it was slow. Actually, I waited for 1 hour, and the process was still running. Is this normal? Thank you.

**Comment by strongcourage** [comment]
@benaneli2024: Yes, this is a well-known performance issue with the SHAP library, as mentioned by the author [here](https://github.com/shap/shap/issues/77#issuecomment-387564691). I also encountered this issue when computing Shapley values for the entire dataset. I would recommend limiting the number of samples used as a background dataset and the number of samples being explained by the SHAP method, as demonstrated in the MAIP GUI. 

<img width="638" alt="Screenshot 2024-03-07 at 13 56 42" src="https://github.com/Montimage/maip/assets/9584484/e1c8b673-56cd-4fa9-8c02-108e1f3e3013">

If you still want to explain the entire dataset, I'm afraid you may need to wait for several hours. Hope this helps.

**Comment by benaneli2024** [comment]
@strongcourage: Good to know. Thank you for the prompt response.
